# Generated by Django 3.0.7 on 2020-06-28 18:59

import blog.models
import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(upload_to='files/categury_covers/', validators=[blog.models.validate_file_ext])),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='files/user_avatar/', validators=[blog.models.validate_file_ext])),
                ('descripion', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('cover', models.FileField(upload_to='files/articles_covers/', validators=[blog.models.validate_file_ext])),
                ('content', ckeditor.fields.RichTextField()),
                ('creat_at', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.userprofile')),
                ('categury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categury')),
            ],
        ),
    ]
